### ISSUE TITLE
글자 나누기 함수 구현 끝, 다음은...?

### ISSUE THREAD

**Issue by estoyun** [ESTO-NETWORK/yamin#5]
계속 view에서 변환하는 함수들 만들어가면 되나요?

**Comment by loopback-kr** [comment]
멍멍이 -> 댕댕이 구현할 것.

**Comment by estoyun** [comment]
아이디어 얻어보려 임시로 함수 만들긴 했지만 [댕,댕,이]까지 구현, [댕댕이]로 합치는 건 31일 커밋으로ㅎ
